### ISSUE TITLE
Update to Zeebe Client 1.0.0

### ISSUE THREAD

**Issue by aivinog1** [camunda-community-hub/zeebe-script-worker#100]
I think that we need to update the zeebe libs to 1.0.0. Why the dependabot is not working?

**Comment by saig0** [comment]
Yes. We need to update the client to Zeebe `1.0.0` :rocket: 

> Why the dependabot is not working?

After moving this repo into the new community hub organization, the build pipeline and dependabot were broken. I'll update the settings soon. Same for other projects in the hub :building_construction:
