### ISSUE TITLE
no script engine found with name 'JavaScript

### ISSUE THREAD

**Issue by coderzpw1** [camunda-community-hub/zeebe-script-worker#170]
What is the reason for reporting "no script engine found with name 'JavaScript'"?

**Comment by saig0** [comment]
@coderzpw1 please share more details about your environment.

How do you run the Zeebe worker?
Do you use the provided Docker image?

It works for me with the latest Docker image `zeebe-script-worker:1.1.0`.

**Comment by coderzpw1** [comment]
This error is caused by the high JDK version. Now it's OK to change to jdk11

**Comment by saig0** [comment]
> This error is caused by the high JDK version. 

True. JavaScript is removed since JDK 15. 

Instead, we could use the Docker image for now. In the future, we need a different way, for example, use [GraalVMs JavaScript](https://www.graalvm.org/javascript/).

**Comment by coderzpw1** [comment]
Ok, I got it. Thank you for your answer.

**Comment by saig0** [comment]
In case, someone is interested to migrate to GraalVM JS, here is a short guide: https://golb.hplar.ch/2020/04/java-javascript-engine.html
